
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.gyula.wildaside.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.common.Mod;

import net.minecraft.world.level.levelgen.feature.Feature;

import net.gyula.wildaside.world.features.plants.YellowGlowingHickorySaplingFeature;
import net.gyula.wildaside.world.features.plants.VibrionSporeholderFeature;
import net.gyula.wildaside.world.features.plants.VibrionRootsFeature;
import net.gyula.wildaside.world.features.plants.SubstiliumSproutsFeature;
import net.gyula.wildaside.world.features.plants.SpottedWintergreenFeature;
import net.gyula.wildaside.world.features.plants.RedGlowingHickorySaplingFeature;
import net.gyula.wildaside.world.features.plants.PanxterFlowerFeature;
import net.gyula.wildaside.world.features.plants.HickorySaplingFeature;
import net.gyula.wildaside.world.features.plants.GreenGlowingHickorySaplingFeature;
import net.gyula.wildaside.world.features.plants.FallenYellowGlowingHickoryLeavesFeature;
import net.gyula.wildaside.world.features.plants.FallenRedGlowingHickoryLeavesFeature;
import net.gyula.wildaside.world.features.plants.FallenHickoryLeavesFeature;
import net.gyula.wildaside.world.features.plants.FallenGreenGlowingHickoryLeavesFeature;
import net.gyula.wildaside.world.features.plants.FallenBrownGlowingHickoryLeavesFeature;
import net.gyula.wildaside.world.features.plants.BrownGlowingHickorySaplingFeature;
import net.gyula.wildaside.world.features.ores.OvergrownEntoriumOreFeature;
import net.gyula.wildaside.world.features.ores.CompressedSubstiliumSoilFeature;
import net.gyula.wildaside.world.features.SubstiliumTreeGrowerStr9Feature;
import net.gyula.wildaside.world.features.SubstiliumTreeGrowerStr8Feature;
import net.gyula.wildaside.world.features.SubstiliumTreeGrowerStr7Feature;
import net.gyula.wildaside.world.features.SubstiliumTreeGrowerStr6Feature;
import net.gyula.wildaside.world.features.SubstiliumTreeGrowerStr5Feature;
import net.gyula.wildaside.world.features.SubstiliumTreeGrowerStr4Feature;
import net.gyula.wildaside.world.features.SubstiliumTreeGrowerStr3Feature;
import net.gyula.wildaside.world.features.SubstiliumTreeGrowerStr2Feature;
import net.gyula.wildaside.world.features.SubstiliumTreeGrowerStr1Feature;
import net.gyula.wildaside.world.features.SubstiliumTreeGrowerStr12Feature;
import net.gyula.wildaside.world.features.SubstiliumTreeGrowerStr11Feature;
import net.gyula.wildaside.world.features.SubstiliumTreeGrowerStr10Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr9Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr8Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr7Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr6Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr5Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr4Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr3Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr39Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr38Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr37Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr36Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr35Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr34Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr33Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr32Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr31Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr30Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr2Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr29Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr28Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr27Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr26Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr25Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr24Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr23Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr22Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr21Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr20Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr1Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr19Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr18Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr17Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr16Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr15Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr12Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr11Feature;
import net.gyula.wildaside.world.features.NaturalSporeblasterStr10Feature;
import net.gyula.wildaside.world.features.HickoryTreeGrowerStr5Feature;
import net.gyula.wildaside.world.features.HickoryTreeGrowerStr4Feature;
import net.gyula.wildaside.world.features.HickoryTreeGrowerStr3Feature;
import net.gyula.wildaside.world.features.HickoryTreeGrowerStr2Feature;
import net.gyula.wildaside.world.features.HickoryTreeGrowerStr1Feature;
import net.gyula.wildaside.world.features.HickoryCabinStrFeature;
import net.gyula.wildaside.world.features.HickoryCabin6Feature;
import net.gyula.wildaside.world.features.HickoryCabin5Feature;
import net.gyula.wildaside.world.features.HickoryCabin4Feature;
import net.gyula.wildaside.world.features.HickoryCabin3Feature;
import net.gyula.wildaside.world.features.HickoryCabin2Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr9Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr8Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr7Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr6Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr69Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr68Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr67Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr66Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr65Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr64Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr63Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr62Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr61Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr60Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr5Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr59Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr58Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr57Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr56Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr55Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr54Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr53Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr52Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr51Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr50Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr4Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr49Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr48Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr47Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr46Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr45Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr44Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr43Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr42Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr41Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr40Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr3Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr39Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr38Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr37Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr36Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr35Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr34Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr33Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr32Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr31Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr30Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr2Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr29Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr28Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr27Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr26Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr25Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr24Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr23Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr22Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr21Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr20Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr1Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr19Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr18Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr17Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr16Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr15Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr14Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr13Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr12Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr11Feature;
import net.gyula.wildaside.world.features.HangingVibrionVegetationGrowerStr10Feature;
import net.gyula.wildaside.world.features.GlowingHickoryTreeGrowerStr3Feature;
import net.gyula.wildaside.world.features.GlowingHickoryTreeGrowerStr2Feature;
import net.gyula.wildaside.world.features.GlowingHickoryTreeGrowerStr1Feature;
import net.gyula.wildaside.WildasideMod;

@Mod.EventBusSubscriber
public class WildasideModFeatures {
	public static final DeferredRegister<Feature<?>> REGISTRY = DeferredRegister.create(ForgeRegistries.FEATURES, WildasideMod.MODID);
	public static final RegistryObject<Feature<?>> VIBRION_ROOTS = REGISTRY.register("vibrion_roots", VibrionRootsFeature::feature);
	public static final RegistryObject<Feature<?>> VIBRION_SPOREHOLDER = REGISTRY.register("vibrion_sporeholder", VibrionSporeholderFeature::feature);
	public static final RegistryObject<Feature<?>> SUBSTILIUM_SPROUTS = REGISTRY.register("substilium_sprouts", SubstiliumSproutsFeature::feature);
	public static final RegistryObject<Feature<?>> OVERGROWN_ENTORIUM_ORE = REGISTRY.register("overgrown_entorium_ore", OvergrownEntoriumOreFeature::feature);
	public static final RegistryObject<Feature<?>> COMPRESSED_SUBSTILIUM_SOIL = REGISTRY.register("compressed_substilium_soil", CompressedSubstiliumSoilFeature::feature);
	public static final RegistryObject<Feature<?>> FALLEN_HICKORY_LEAVES = REGISTRY.register("fallen_hickory_leaves", FallenHickoryLeavesFeature::feature);
	public static final RegistryObject<Feature<?>> FALLEN_RED_GLOWING_HICKORY_LEAVES = REGISTRY.register("fallen_red_glowing_hickory_leaves", FallenRedGlowingHickoryLeavesFeature::feature);
	public static final RegistryObject<Feature<?>> FALLEN_BROWN_GLOWING_HICKORY_LEAVES = REGISTRY.register("fallen_brown_glowing_hickory_leaves", FallenBrownGlowingHickoryLeavesFeature::feature);
	public static final RegistryObject<Feature<?>> FALLEN_YELLOW_GLOWING_HICKORY_LEAVES = REGISTRY.register("fallen_yellow_glowing_hickory_leaves", FallenYellowGlowingHickoryLeavesFeature::feature);
	public static final RegistryObject<Feature<?>> FALLEN_GREEN_GLOWING_HICKORY_LEAVES = REGISTRY.register("fallen_green_glowing_hickory_leaves", FallenGreenGlowingHickoryLeavesFeature::feature);
	public static final RegistryObject<Feature<?>> HICKORY_SAPLING = REGISTRY.register("hickory_sapling", HickorySaplingFeature::feature);
	public static final RegistryObject<Feature<?>> RED_GLOWING_HICKORY_SAPLING = REGISTRY.register("red_glowing_hickory_sapling", RedGlowingHickorySaplingFeature::feature);
	public static final RegistryObject<Feature<?>> BROWN_GLOWING_HICKORY_SAPLING = REGISTRY.register("brown_glowing_hickory_sapling", BrownGlowingHickorySaplingFeature::feature);
	public static final RegistryObject<Feature<?>> YELLOW_GLOWING_HICKORY_SAPLING = REGISTRY.register("yellow_glowing_hickory_sapling", YellowGlowingHickorySaplingFeature::feature);
	public static final RegistryObject<Feature<?>> GREEN_GLOWING_HICKORY_SAPLING = REGISTRY.register("green_glowing_hickory_sapling", GreenGlowingHickorySaplingFeature::feature);
	public static final RegistryObject<Feature<?>> PANXTER_FLOWER = REGISTRY.register("panxter_flower", PanxterFlowerFeature::feature);
	public static final RegistryObject<Feature<?>> SPOTTED_WINTERGREEN = REGISTRY.register("spotted_wintergreen", SpottedWintergreenFeature::feature);
	public static final RegistryObject<Feature<?>> HICKORY_TREE_GROWER_STR_1 = REGISTRY.register("hickory_tree_grower_str_1", HickoryTreeGrowerStr1Feature::feature);
	public static final RegistryObject<Feature<?>> HICKORY_TREE_GROWER_STR_2 = REGISTRY.register("hickory_tree_grower_str_2", HickoryTreeGrowerStr2Feature::feature);
	public static final RegistryObject<Feature<?>> GLOWING_HICKORY_TREE_GROWER_STR_1 = REGISTRY.register("glowing_hickory_tree_grower_str_1", GlowingHickoryTreeGrowerStr1Feature::feature);
	public static final RegistryObject<Feature<?>> GLOWING_HICKORY_TREE_GROWER_STR_2 = REGISTRY.register("glowing_hickory_tree_grower_str_2", GlowingHickoryTreeGrowerStr2Feature::feature);
	public static final RegistryObject<Feature<?>> GLOWING_HICKORY_TREE_GROWER_STR_3 = REGISTRY.register("glowing_hickory_tree_grower_str_3", GlowingHickoryTreeGrowerStr3Feature::feature);
	public static final RegistryObject<Feature<?>> SUBSTILIUM_TREE_GROWER_STR_1 = REGISTRY.register("substilium_tree_grower_str_1", SubstiliumTreeGrowerStr1Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_1 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_1", HangingVibrionVegetationGrowerStr1Feature::feature);
	public static final RegistryObject<Feature<?>> SUBSTILIUM_TREE_GROWER_STR_2 = REGISTRY.register("substilium_tree_grower_str_2", SubstiliumTreeGrowerStr2Feature::feature);
	public static final RegistryObject<Feature<?>> SUBSTILIUM_TREE_GROWER_STR_3 = REGISTRY.register("substilium_tree_grower_str_3", SubstiliumTreeGrowerStr3Feature::feature);
	public static final RegistryObject<Feature<?>> SUBSTILIUM_TREE_GROWER_STR_4 = REGISTRY.register("substilium_tree_grower_str_4", SubstiliumTreeGrowerStr4Feature::feature);
	public static final RegistryObject<Feature<?>> SUBSTILIUM_TREE_GROWER_STR_5 = REGISTRY.register("substilium_tree_grower_str_5", SubstiliumTreeGrowerStr5Feature::feature);
	public static final RegistryObject<Feature<?>> SUBSTILIUM_TREE_GROWER_STR_6 = REGISTRY.register("substilium_tree_grower_str_6", SubstiliumTreeGrowerStr6Feature::feature);
	public static final RegistryObject<Feature<?>> SUBSTILIUM_TREE_GROWER_STR_7 = REGISTRY.register("substilium_tree_grower_str_7", SubstiliumTreeGrowerStr7Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_2 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_2", HangingVibrionVegetationGrowerStr2Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_3 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_3", HangingVibrionVegetationGrowerStr3Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_4 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_4", HangingVibrionVegetationGrowerStr4Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_5 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_5", HangingVibrionVegetationGrowerStr5Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_6 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_6", HangingVibrionVegetationGrowerStr6Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_7 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_7", HangingVibrionVegetationGrowerStr7Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_8 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_8", HangingVibrionVegetationGrowerStr8Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_9 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_9", HangingVibrionVegetationGrowerStr9Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_10 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_10", HangingVibrionVegetationGrowerStr10Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_11 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_11", HangingVibrionVegetationGrowerStr11Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_12 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_12", HangingVibrionVegetationGrowerStr12Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_13 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_13", HangingVibrionVegetationGrowerStr13Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_14 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_14", HangingVibrionVegetationGrowerStr14Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_15 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_15", HangingVibrionVegetationGrowerStr15Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_16 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_16", HangingVibrionVegetationGrowerStr16Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_17 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_17", HangingVibrionVegetationGrowerStr17Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_18 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_18", HangingVibrionVegetationGrowerStr18Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_19 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_19", HangingVibrionVegetationGrowerStr19Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_20 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_20", HangingVibrionVegetationGrowerStr20Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_21 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_21", HangingVibrionVegetationGrowerStr21Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_22 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_22", HangingVibrionVegetationGrowerStr22Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_23 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_23", HangingVibrionVegetationGrowerStr23Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_24 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_24", HangingVibrionVegetationGrowerStr24Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_25 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_25", HangingVibrionVegetationGrowerStr25Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_26 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_26", HangingVibrionVegetationGrowerStr26Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_27 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_27", HangingVibrionVegetationGrowerStr27Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_28 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_28", HangingVibrionVegetationGrowerStr28Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_29 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_29", HangingVibrionVegetationGrowerStr29Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_30 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_30", HangingVibrionVegetationGrowerStr30Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_31 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_31", HangingVibrionVegetationGrowerStr31Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_32 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_32", HangingVibrionVegetationGrowerStr32Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_33 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_33", HangingVibrionVegetationGrowerStr33Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_34 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_34", HangingVibrionVegetationGrowerStr34Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_35 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_35", HangingVibrionVegetationGrowerStr35Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_1 = REGISTRY.register("natural_sporeblaster_str_1", NaturalSporeblasterStr1Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_2 = REGISTRY.register("natural_sporeblaster_str_2", NaturalSporeblasterStr2Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_3 = REGISTRY.register("natural_sporeblaster_str_3", NaturalSporeblasterStr3Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_4 = REGISTRY.register("natural_sporeblaster_str_4", NaturalSporeblasterStr4Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_5 = REGISTRY.register("natural_sporeblaster_str_5", NaturalSporeblasterStr5Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_6 = REGISTRY.register("natural_sporeblaster_str_6", NaturalSporeblasterStr6Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_7 = REGISTRY.register("natural_sporeblaster_str_7", NaturalSporeblasterStr7Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_8 = REGISTRY.register("natural_sporeblaster_str_8", NaturalSporeblasterStr8Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_9 = REGISTRY.register("natural_sporeblaster_str_9", NaturalSporeblasterStr9Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_10 = REGISTRY.register("natural_sporeblaster_str_10", NaturalSporeblasterStr10Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_11 = REGISTRY.register("natural_sporeblaster_str_11", NaturalSporeblasterStr11Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_12 = REGISTRY.register("natural_sporeblaster_str_12", NaturalSporeblasterStr12Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_15 = REGISTRY.register("natural_sporeblaster_str_15", NaturalSporeblasterStr15Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_16 = REGISTRY.register("natural_sporeblaster_str_16", NaturalSporeblasterStr16Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_17 = REGISTRY.register("natural_sporeblaster_str_17", NaturalSporeblasterStr17Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_18 = REGISTRY.register("natural_sporeblaster_str_18", NaturalSporeblasterStr18Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_19 = REGISTRY.register("natural_sporeblaster_str_19", NaturalSporeblasterStr19Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_20 = REGISTRY.register("natural_sporeblaster_str_20", NaturalSporeblasterStr20Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_21 = REGISTRY.register("natural_sporeblaster_str_21", NaturalSporeblasterStr21Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_22 = REGISTRY.register("natural_sporeblaster_str_22", NaturalSporeblasterStr22Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_23 = REGISTRY.register("natural_sporeblaster_str_23", NaturalSporeblasterStr23Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_24 = REGISTRY.register("natural_sporeblaster_str_24", NaturalSporeblasterStr24Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_25 = REGISTRY.register("natural_sporeblaster_str_25", NaturalSporeblasterStr25Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_26 = REGISTRY.register("natural_sporeblaster_str_26", NaturalSporeblasterStr26Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_27 = REGISTRY.register("natural_sporeblaster_str_27", NaturalSporeblasterStr27Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_28 = REGISTRY.register("natural_sporeblaster_str_28", NaturalSporeblasterStr28Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_29 = REGISTRY.register("natural_sporeblaster_str_29", NaturalSporeblasterStr29Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_36 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_36", HangingVibrionVegetationGrowerStr36Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_37 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_37", HangingVibrionVegetationGrowerStr37Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_38 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_38", HangingVibrionVegetationGrowerStr38Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_39 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_39", HangingVibrionVegetationGrowerStr39Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_40 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_40", HangingVibrionVegetationGrowerStr40Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_41 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_41", HangingVibrionVegetationGrowerStr41Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_42 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_42", HangingVibrionVegetationGrowerStr42Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_43 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_43", HangingVibrionVegetationGrowerStr43Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_44 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_44", HangingVibrionVegetationGrowerStr44Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_45 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_45", HangingVibrionVegetationGrowerStr45Feature::feature);
	public static final RegistryObject<Feature<?>> HICKORY_TREE_GROWER_STR_3 = REGISTRY.register("hickory_tree_grower_str_3", HickoryTreeGrowerStr3Feature::feature);
	public static final RegistryObject<Feature<?>> HICKORY_TREE_GROWER_STR_4 = REGISTRY.register("hickory_tree_grower_str_4", HickoryTreeGrowerStr4Feature::feature);
	public static final RegistryObject<Feature<?>> HICKORY_TREE_GROWER_STR_5 = REGISTRY.register("hickory_tree_grower_str_5", HickoryTreeGrowerStr5Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_30 = REGISTRY.register("natural_sporeblaster_str_30", NaturalSporeblasterStr30Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_31 = REGISTRY.register("natural_sporeblaster_str_31", NaturalSporeblasterStr31Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_32 = REGISTRY.register("natural_sporeblaster_str_32", NaturalSporeblasterStr32Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_33 = REGISTRY.register("natural_sporeblaster_str_33", NaturalSporeblasterStr33Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_34 = REGISTRY.register("natural_sporeblaster_str_34", NaturalSporeblasterStr34Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_35 = REGISTRY.register("natural_sporeblaster_str_35", NaturalSporeblasterStr35Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_36 = REGISTRY.register("natural_sporeblaster_str_36", NaturalSporeblasterStr36Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_37 = REGISTRY.register("natural_sporeblaster_str_37", NaturalSporeblasterStr37Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_38 = REGISTRY.register("natural_sporeblaster_str_38", NaturalSporeblasterStr38Feature::feature);
	public static final RegistryObject<Feature<?>> NATURAL_SPOREBLASTER_STR_39 = REGISTRY.register("natural_sporeblaster_str_39", NaturalSporeblasterStr39Feature::feature);
	public static final RegistryObject<Feature<?>> SUBSTILIUM_TREE_GROWER_STR_8 = REGISTRY.register("substilium_tree_grower_str_8", SubstiliumTreeGrowerStr8Feature::feature);
	public static final RegistryObject<Feature<?>> SUBSTILIUM_TREE_GROWER_STR_9 = REGISTRY.register("substilium_tree_grower_str_9", SubstiliumTreeGrowerStr9Feature::feature);
	public static final RegistryObject<Feature<?>> SUBSTILIUM_TREE_GROWER_STR_10 = REGISTRY.register("substilium_tree_grower_str_10", SubstiliumTreeGrowerStr10Feature::feature);
	public static final RegistryObject<Feature<?>> SUBSTILIUM_TREE_GROWER_STR_11 = REGISTRY.register("substilium_tree_grower_str_11", SubstiliumTreeGrowerStr11Feature::feature);
	public static final RegistryObject<Feature<?>> SUBSTILIUM_TREE_GROWER_STR_12 = REGISTRY.register("substilium_tree_grower_str_12", SubstiliumTreeGrowerStr12Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_46 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_46", HangingVibrionVegetationGrowerStr46Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_47 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_47", HangingVibrionVegetationGrowerStr47Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_48 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_48", HangingVibrionVegetationGrowerStr48Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_49 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_49", HangingVibrionVegetationGrowerStr49Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_50 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_50", HangingVibrionVegetationGrowerStr50Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_51 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_51", HangingVibrionVegetationGrowerStr51Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_52 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_52", HangingVibrionVegetationGrowerStr52Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_53 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_53", HangingVibrionVegetationGrowerStr53Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_54 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_54", HangingVibrionVegetationGrowerStr54Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_55 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_55", HangingVibrionVegetationGrowerStr55Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_56 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_56", HangingVibrionVegetationGrowerStr56Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_57 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_57", HangingVibrionVegetationGrowerStr57Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_58 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_58", HangingVibrionVegetationGrowerStr58Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_59 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_59", HangingVibrionVegetationGrowerStr59Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_60 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_60", HangingVibrionVegetationGrowerStr60Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_61 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_61", HangingVibrionVegetationGrowerStr61Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_62 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_62", HangingVibrionVegetationGrowerStr62Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_63 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_63", HangingVibrionVegetationGrowerStr63Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_64 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_64", HangingVibrionVegetationGrowerStr64Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_65 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_65", HangingVibrionVegetationGrowerStr65Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_66 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_66", HangingVibrionVegetationGrowerStr66Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_67 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_67", HangingVibrionVegetationGrowerStr67Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_68 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_68", HangingVibrionVegetationGrowerStr68Feature::feature);
	public static final RegistryObject<Feature<?>> HANGING_VIBRION_VEGETATION_GROWER_STR_69 = REGISTRY.register("hanging_vibrion_vegetation_grower_str_69", HangingVibrionVegetationGrowerStr69Feature::feature);
	public static final RegistryObject<Feature<?>> HICKORY_CABIN_STR = REGISTRY.register("hickory_cabin_str", HickoryCabinStrFeature::feature);
	public static final RegistryObject<Feature<?>> HICKORY_CABIN_2 = REGISTRY.register("hickory_cabin_2", HickoryCabin2Feature::feature);
	public static final RegistryObject<Feature<?>> HICKORY_CABIN_3 = REGISTRY.register("hickory_cabin_3", HickoryCabin3Feature::feature);
	public static final RegistryObject<Feature<?>> HICKORY_CABIN_4 = REGISTRY.register("hickory_cabin_4", HickoryCabin4Feature::feature);
	public static final RegistryObject<Feature<?>> HICKORY_CABIN_5 = REGISTRY.register("hickory_cabin_5", HickoryCabin5Feature::feature);
	public static final RegistryObject<Feature<?>> HICKORY_CABIN_6 = REGISTRY.register("hickory_cabin_6", HickoryCabin6Feature::feature);
}
